"""adiciona coluna foto_perfil em usuarios

Revision ID: 361d3f7a4a7b
Revises: 49442db8c681
Create Date: 2026-04-15 17:25:17.407765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '361d3f7a4a7b'
down_revision = '49442db8c681'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('ativo',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('criado_em',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=1)
        batch_op.alter_column('criado_em',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('ativo',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
        batch_op.alter_column('nome',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)

    # ### end Alembic commands ###
