"""adicionando datas em empresas

Revision ID: 8874e1e5592b
Revises: bf52be2227a6
Create Date: 2026-03-24 16:48:19.456540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8874e1e5592b'
down_revision = 'bf52be2227a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('criado_em', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('atualizado_em', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.drop_column('atualizado_em')
        batch_op.drop_column('criado_em')

    # ### end Alembic commands ###
